version: '3.3' #docker-compose 版本
services:
  cldapp:
    build: . #表示执行的当前目录下的Dockerfile 文件
    #    build:
    #      dockerfile: #指定具体的dockerfile文件
    image: cldapp #表示生成的镜像的名字
    depends_on:
      - redis
    ports:
      - "9090:8080" #项目8080端口映射到外部访问9090
  redis:
    image: "redis:alpine" #使用精简版本的redis