server:
  port: 8089
spring:
  datasource:
#    url: jdbc:dm://127.0.0.1:5236/DMHR?useUnicode=true
#    url: jdbc:dm://127.0.0.1:5236/DMHR?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
#    url: jdbc:dm://192.168.10.11:5236/DMHR?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
#    url: jdbc:dm://127.0.0.1:5236/DMSERVER?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    url: jdbc:dm://127.0.0.1:5236/DMHR?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: SYSDBA
    password: SYSDBA
    driver-class-name: dm.jdbc.driver.DmDriver
#        ConnectionTestQuery: SELECT 1
#mybatis:
  # \u6307\u5B9Asql\u6620\u5C04\u6587\u4EF6\u4F4D\u7F6E
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.dc.entity

# log4j\u6253\u5370sql
#logging:
#  level:
#    com.dc.mapper.**: debug
