apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pc-ReplicaSet #ReplicaSet的名字
  namespace: dev
  labels: #给ReplicaSet打标签
    env: "rs001"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: re-nginx-001
  template:
    metadata:
      labels:
        app: re-nginx-001
    spec:
      containers:
        - name: contain-nginx-002
          image: nginx:1.17.1