apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany # 表示这个共享的nfs可以被多个节点挂载，可读可写
  persistentVolumeReclaimPolicy: Retain  # 回收策略 保留，
  nfs:
    path: /root/data/pv1
    server: 192.168.196.129
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /root/data/pv2
    server: 192.168.196.129
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-pv3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /root/data/pv3
    server: 192.168.196.129